# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Your own specialized rules go here
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  Include:
    - "app/**/*"
    - "config/routes.rb"
    - "lib/**/*"
    - "test/**/*"
    - "Gemfile"
