default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    database: chat_app_development
  cache:
    <<: *primary_development
    database: chat_app_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: chat_app_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: chat_app_development_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: chat_app_test

production:
  primary: &primary_production
    <<: *default
    database: chat_app_production
    username: chat_app
    password: <%= ENV["CHAT_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: chat_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: chat_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: chat_app_production_cable
    migrations_paths: db/cable_migrate
